FROM maven:3.9.5-eclipse-temurin-17 AS build

WORKDIR /app
COPY pom.xml ./
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

EXPOSE 8080

WORKDIR /app
COPY --from=build /app/target/bot-0.0.1-SNAPSHOT.jar app.jar

COPY --from=build /app/src/main/resources/mensagens.txt /app/mensagens/mensagens.txt

ENTRYPOINT ["java", "-jar", "app.jar"]
