# Etapa de build
FROM ubuntu:latest AS build

# Instala as dependências
RUN apt-get update
RUN apt-get install -y openjdk-17-jdk maven

# Verifica se o Maven e o Java estão instalados corretamente
RUN mvn -v
RUN java -version

# Copia os arquivos do projeto
COPY . /app
WORKDIR /app/bot-IARA   # Se seu pom.xml estiver em bot-IARA, altere o diretório de trabalho

# Executa o Maven para compilar o projeto e detalha o erro
RUN mvn clean install -e -X

# Etapa de execução
FROM openjdk:17-jdk-slim

# Expondo a porta
EXPOSE 8080

# Copia o JAR gerado da etapa de build
COPY --from=build /app/bot-IARA/target/deploy_render-1.0.0.jar app.jar

# Executa o JAR
ENTRYPOINT [ "java", "-jar", "app.jar" ]
